# Site settings
title: Matthew D. McHugh
email: mchughm@nursing.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
  Independence Chair for Nursing Education, Professor of Nursing
  Associate Director, Center for Health Outcomes & Policy Research
  University of Pennsylvania School of Nursing.
  I study the contribution of nurses to improving patient outcomes. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.nursing.upenn.edu/live/profiles/92-matthew-d-mchugh" # the base hostname & protocol for your site
twitter_username: matthewdmchugh
github_username:  mchughmatthew
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
